apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "sample-nodejs.fullname" . }}
  labels:
    {{- include "sample-nodejs.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "sample-nodejs.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "sample-nodejs.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: sample-nodejs

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /live
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
            {{- toYaml .Values.resources | nindent 12 }}